#
# Module manifest for module 'ProgramD-x86'
#
# Generated by: MarcusW
#
# Generated on: 18/03/2019
#

@{

# Version number of this module.
ModuleVersion = '1.0'

# ID used to uniquely identify this module
GUID = 'c96409c2-57b7-43bd-a259-d82d851a7441'

# Author of this module
Author = 'Marcus W'

# Copyright statement for this module
Copyright = '(c) 2015 MarcusW.'

# Description of the functionality provided by this module
Description = 'This environment module gives you access to the "ProjectC" modules.'

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @("EnvironmentModuleCore")

# List of all modules packaged with this module
ModuleList = @("ProgramD-x86")

}

