#
# Module manifest for module 'ProgramZ-3_6-x64'
#
# Generated by: MarcusW
#
# Generated on: 06/02/2020
#

@{

# Version number of this module.
ModuleVersion = '1.0'

# ID used to uniquely identify this module
GUID = 'f9f64800-530e-4b59-94a5-1d195f389bc7'

# Author of this module
Author = 'Marcus W'

# Copyright statement for this module
Copyright = '(c) 2020 MarcusW.'

# Description of the functionality provided by this module
Description = 'This environment module gives you access to the "ProgramZ-3_6-x64" modules.'

# Modules that must be imported into the global environment prior to importing this module
PrivateData = @{
  PSData = @{
    ExternalModuleDependencies = @('EnvironmentModuleCore')
  }
}

# List of all modules packaged with this module
ModuleList = @("ProgramZ-3_6-x64")

}

