#
# Module manifest for module 'App-1.3-x64'
#
# Generated by: MarcusW
#
# Generated on: 06/02/2020
#

@{

# Script module or binary module file associated with this manifest
RootModule = 'App-1.3-x64.psm1'

# Version number of this module.
ModuleVersion = '1.0'

# ID used to uniquely identify this module
GUID = 'd2ac1da2-bb51-43cd-ac5f-eaaa182c7b85'

# Author of this module
Author = 'Marcus W'

# Copyright statement for this module
Copyright = '(c) 2020 MarcusW.'

# Description of the functionality provided by this module
Description = 'This environment module gives you access to the "ProjectH" modules.'

# Modules that must be imported into the global environment prior to importing this module
PrivateData = @{
  PSData = @{
    ExternalModuleDependencies = @('EnvironmentModuleCore')
  }
}

# List of all modules packaged with this module
ModuleList = @("App-1.3-x64")

}

