#
# Module manifest for module 'ProgramH-x64'
#
# Generated by: MarcusW
#
# Generated on: 06/02/2020
#

@{

# Script module or binary module file associated with this manifest
RootModule = 'ProgramH.psm1'

# Version number of this module.
ModuleVersion = '1.0'

# ID used to uniquely identify this module
GUID = '284171e7-5f03-41d5-9dd3-614b45f07c8d'

# Author of this module
Author = 'Marcus W'

# Copyright statement for this module
Copyright = '(c) 2020 MarcusW.'

# Description of the functionality provided by this module
Description = 'This environment module gives you access to the "ProjectH" modules.'

# Modules that must be imported into the global environment prior to importing this module
PrivateData = @{
  PSData = @{
    ExternalModuleDependencies = @('EnvironmentModuleCore')
  }
}

# List of all modules packaged with this module
ModuleList = @("ProgramH")

}

