#
# Module manifest for module 'ProgramZCode-3_11-x64'
#
# Generated by: MarcusW
#
# Generated on: 06/02/2020
#

@{

# Version number of this module.
ModuleVersion = '1.0'

# ID used to uniquely identify this module
GUID = 'c84658f0-9e58-4e9e-92f1-0bdaabbe8c70'

# Author of this module
Author = 'Marcus W'

# Copyright statement for this module
Copyright = '(c) 2020 MarcusW.'

# Description of the functionality provided by this module
Description = 'This environment module gives you access to the "ProgramZCode-3_11-x64" modules.'

# Modules that must be imported into the global environment prior to importing this module
PrivateData = @{
  PSData = @{
    ExternalModuleDependencies = @('EnvironmentModuleCore')
  }
}

# List of all modules packaged with this module
ModuleList = @("ProgramZCode-3_11-x64")

}

