#
# Module manifest for module 'ProgramF-1.0.3'
#
# Generated by: MarcusW
#
# Generated on: 18/03/2019
#

@{

# Script module or binary module file associated with this manifest
RootModule = 'ProgramF-1.0.3.psm1'

# Version number of this module.
ModuleVersion = '1.0'

# ID used to uniquely identify this module
GUID = 'd42e34d4-5ed1-4fde-8499-7afb84be9265'

# Author of this module
Author = 'Marcus W'

# Copyright statement for this module
Copyright = '(c) 2015 MarcusW.'

# Description of the functionality provided by this module
Description = 'This environment module gives you access to the "ProjectC" modules.'

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @("EnvironmentModuleCore")

# List of all modules packaged with this module
ModuleList = @("ProgramF-1.0.3")

}

