#
# Module manifest for module 'DependencyChildB'
#
# Generated by: MarcusW
#
# Generated on: 12/08/2015
#

@{

# Script module or binary module file associated with this manifest

# Version number of this module.
ModuleVersion = '1.0'

# ID used to uniquely identify this module
GUID = '5704cf71-4872-4968-8e4b-fb85220f10ad'

# Author of this module
Author = 'Marcus W'

# Copyright statement for this module
Copyright = '(c) 2015 MarcusW. All rights reserved.'

# Description of the functionality provided by this module
Description = 'This environment module gives you access to the "DependencyChildB" module.'

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @("EnvironmentModules")

# List of all modules packaged with this module
ModuleList = @("DependencyChildB")

}

