#
# Module manifest for module 'DependencyBase'
#
# Generated by: MarcusW
#
# Generated on: 12/08/2015
#

@{

# Script module or binary module file associated with this manifest

# Version number of this module.
ModuleVersion = '1.0'

# ID used to uniquely identify this module
GUID = 'b8194b41-8ad3-40b6-b9e5-661e84234ecd'

# Author of this module
Author = 'Marcus W'

# Copyright statement for this module
Copyright = '(c) 2015 MarcusW. All rights reserved.'

# Description of the functionality provided by this module
Description = 'This environment module gives you access to the "DependencyBase" module.'

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @("EnvironmentModules")

# List of all modules packaged with this module
ModuleList = @("DependencyBase")

}

