#
# Module manifest for module 'ProgramD-x64'
#
# Generated by: MarcusW
#
# Generated on: 18/03/2019
#

@{

# Script module or binary module file associated with this manifest
RootModule = 'ProgramD-x64.psm1'

# Version number of this module.
ModuleVersion = '1.0'

# ID used to uniquely identify this module
GUID = 'ee382f9d-5f28-4c93-9199-ee130ca11e03'

# Author of this module
Author = 'Marcus W'

# Copyright statement for this module
Copyright = '(c) 2015 MarcusW.'

# Description of the functionality provided by this module
Description = 'This environment module gives you access to the "ProjectC" modules.'

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @("EnvironmentModuleCore")

# List of all modules packaged with this module
ModuleList = @("ProgramD-x64")

}

