#
# Module manifest for module 'ProgramE-x64'
#
# Generated by: MarcusW
#
# Generated on: 12/08/2015
#

@{

    # Version number of this module.
    ModuleVersion = '1.0'

    # ID used to uniquely identify this module
    GUID = 'cbb3015a-2618-4ece-9317-ef98b4d92ba8'

    # Author of this module
    Author = 'Marcus W'

    # Copyright statement for this module
    Copyright = '(c) 2015 MarcusW. All rights reserved.'

    # Description of the functionality provided by this module
    Description = 'This environment module gives you access to the "ProjectC" modules.'

    # Modules that must be imported into the global environment prior to importing this module
    RequiredModules = @("EnvironmentModules")

    # List of all modules packaged with this module
    ModuleList = @("ProgramE-x64")

}

